# Generated by Django 2.2.4 on 2019-08-22 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0002_auto_20190819_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Author.Profile'),
        ),
    ]
